# Generated by Django 6.0.6 on 2026-06-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sudoku', 'Sudoku'), ('speed_math', 'Speed Math'), ('logic', 'Logic Puzzle'), ('memory', 'Memory Match')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('data', models.JSONField()),
                ('solution', models.JSONField()),
                ('hint_text', models.TextField(blank=True)),
                ('time_limit', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['type', 'difficulty'],
            },
        ),
    ]
