# Generated by Django 6.0.6 on 2026-06-26 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('first_game', '🎮 First Game'), ('streak_3', '🔥 3-Day Streak'), ('streak_7', '⚡ 7-Day Streak'), ('streak_30', '👑 30-Day Streak'), ('score_100', '💯 Score 100'), ('score_1000', '🚀 Score 1000'), ('speed_demon', '⚡ Speed Demon'), ('perfectionist', '✨ Perfect Solve'), ('brain_master', '🧠 Brain Master')], max_length=30)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='users.user')),
            ],
            options={
                'unique_together': {('user', 'badge_type')},
            },
        ),
    ]
